# Generated by Django 3.0.4 on 2020-03-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Things',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('deadline', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('remind', models.CharField(max_length=200, null=True)),
                ('tag', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
