# Generated by Django 3.0.4 on 2020-03-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='deadline',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='things',
            name='time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
